os: linux
services:
  - docker
install: skip
before_install:
  - docker version
  - chmod 755 test.sh
  - ./test.sh
script: docker version

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
